### PR TITLE
chore: update to rxjs 6 and axios 0.18

### PR DESCRIPTION
**Pull request by markfknight**
Hi, 

I see there is a pull request open for RxJS 6 Alpha with conflicts, thought I would submit a PR for RxJS 6 now it is released. 

Have bumped peer dependancies to Axios 0.18.0 and RxJS 6 also update the dev dependancies while I was at it. 

All tests passing, comments welcome! 

Thanks, 
Mark

### CODE REVIEW

**Comment by karlos1337** [comment]
Since I need this functionality too I fork the repo and apply this PR and @tentenponce one in https://github.com/karlos1337/rxios , glad to remove it when @davguij apply the PR's here.

**Comment by markfknight** [comment]
@davguij do you have any feedback for this pull request, or should i close?

**Comment by 0x006EA1E5** [comment]
Will you guys be cutting a release for this anytime soon?  Thanks  :D

**Comment by davguij** [comment]
Sorry for so much time without any updates from my side. 

[v2.0.0](https://github.com/davguij/rxios/releases/tag/v2.0.0) should fix this.

**Pull request closed without merging**
